import React, { useEffect, useState, useCallback } from 'react';
import axios from 'axios';
import {
  BellRing,
  Search,
  Filter,
  CheckCircle2,
  AlertTriangle,
  Clock,
  X,
  ChevronDown,
  ChevronUp,
  ShieldAlert,
  Server
} from 'lucide-react';

const Alerts = () => {
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  
  // Filters
  const [statusFilter, setStatusFilter] = useState('');
  const [severityFilter, setSeverityFilter] = useState('');
  
  // Pagination
  const [page, setPage] = useState(0);
  const [totalPages, setTotalPages] = useState(1);
  const size = 15;

  const fetchAlerts = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const params = { page, size };
      if (statusFilter) params.status = statusFilter;
      if (severityFilter) params.severity = severityFilter;
      
      const response = await axios.get('/api/alerts', { params });
      const payload = response.data;
      
      setAlerts(Array.isArray(payload) ? payload : payload.content || []);
      setTotalPages(payload.totalPages || 1);
    } catch (err) {
      console.error(err);
      setError('Failed to fetch alerts. ' + (err.response?.data?.message || err.message));
    } finally {
      setLoading(false);
    }
  }, [page, size, statusFilter, severityFilter]);

  useEffect(() => {
    fetchAlerts();
  }, [fetchAlerts]);

  const updateAlertStatus = async (id, newStatus) => {
    try {
      await axios.put(`/api/alerts/${id}/status`, { status: newStatus });
      fetchAlerts();
    } catch (err) {
      console.error(err);
      alert('Failed to update alert status: ' + (err.response?.data?.message || err.message));
    }
  };

  const getSeverityStyle = (severity) => {
    switch (severity?.toUpperCase()) {
      case 'CRITICAL':
        return 'text-red-400 bg-red-500/10 border-red-500/20';
      case 'HIGH':
        return 'text-orange-400 bg-orange-500/10 border-orange-500/20';
      case 'MEDIUM':
        return 'text-yellow-400 bg-yellow-500/10 border-yellow-500/20';
      case 'LOW':
        return 'text-blue-400 bg-blue-500/10 border-blue-500/20';
      default:
        return 'text-slate-400 bg-slate-500/10 border-slate-500/20';
    }
  };
  
  const getSeverityIcon = (severity) => {
    switch (severity?.toUpperCase()) {
      case 'CRITICAL':
        return <ShieldAlert className="w-4 h-4 mr-1 text-red-500" />;
      case 'HIGH':
        return <AlertTriangle className="w-4 h-4 mr-1 text-orange-500" />;
      case 'MEDIUM':
        return <AlertTriangle className="w-4 h-4 mr-1 text-yellow-500" />;
      case 'LOW':
        return <BellRing className="w-4 h-4 mr-1 text-blue-500" />;
      default:
        return <BellRing className="w-4 h-4 mr-1 text-slate-500" />;
    }
  };

  const getStatusStyle = (status) => {
    switch (status?.toUpperCase()) {
      case 'NEW':
        return 'text-red-400';
      case 'INVESTIGATING':
        return 'text-yellow-400';
      case 'RESOLVED':
        return 'text-green-400';
      case 'FALSE_POSITIVE':
        return 'text-slate-400';
      default:
        return 'text-slate-400';
    }
  };

  return (
    <div className="space-y-6">
      {/* Header Section */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold text-white flex items-center">
            <BellRing className="mr-2 text-indigo-400 w-6 h-6" />
            Analyst Queue
          </h1>
          <p className="text-sm text-slate-400 mt-1">
            Prioritized security alerts generated by the Sentinel Alert Engine.
          </p>
        </div>
      </div>

      {/* Filters */}
      <div className="glass-card p-4 flex flex-wrap gap-4 items-center">
        <div className="flex items-center space-x-2">
          <Filter className="w-4 h-4 text-slate-400" />
          <span className="text-sm text-slate-300">Filter By:</span>
        </div>

        <select
          value={statusFilter}
          onChange={(e) => { setStatusFilter(e.target.value); setPage(0); }}
          className="bg-slate-900/50 border border-slate-700/50 rounded-lg px-3 py-1.5 text-sm text-slate-300 outline-none focus:border-indigo-500 transition-colors"
        >
          <option value="">All Statuses</option>
          <option value="NEW">New</option>
          <option value="INVESTIGATING">Investigating</option>
          <option value="RESOLVED">Resolved</option>
          <option value="FALSE_POSITIVE">False Positive</option>
        </select>

        <select
          value={severityFilter}
          onChange={(e) => { setSeverityFilter(e.target.value); setPage(0); }}
          className="bg-slate-900/50 border border-slate-700/50 rounded-lg px-3 py-1.5 text-sm text-slate-300 outline-none focus:border-indigo-500 transition-colors"
        >
          <option value="">All Severities</option>
          <option value="CRITICAL">Critical</option>
          <option value="HIGH">High</option>
          <option value="MEDIUM">Medium</option>
          <option value="LOW">Low</option>
        </select>
        
        <button
          onClick={() => { setStatusFilter(''); setSeverityFilter(''); setPage(0); }}
          className="text-slate-400 hover:text-white text-sm flex items-center transition-colors"
        >
          <X className="w-4 h-4 mr-1" />
          Clear
        </button>
      </div>

      {/* Main Content */}
      <div className="glass-card overflow-hidden">
        {error ? (
          <div className="p-4 mx-4 mt-4 bg-red-500/10 border border-red-500/20 text-red-400 rounded-lg text-sm flex items-center">
            <AlertTriangle className="w-5 h-5 mr-2 shrink-0" />
            {error}
          </div>
        ) : null}

        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm whitespace-nowrap">
            <thead className="bg-slate-900/50 border-b border-slate-700/50">
              <tr>
                <th className="py-4 px-6 text-slate-300 font-medium tracking-wide">Alert ID</th>
                <th className="py-4 px-6 text-slate-300 font-medium tracking-wide">Severity</th>
                <th className="py-4 px-6 text-slate-300 font-medium tracking-wide">Description</th>
                <th className="py-4 px-6 text-slate-300 font-medium tracking-wide">Source IP</th>
                <th className="py-4 px-6 text-slate-300 font-medium tracking-wide">Status</th>
                <th className="py-4 px-6 text-slate-300 font-medium tracking-wide">Last Updated</th>
                <th className="py-4 px-6 text-slate-300 font-medium tracking-wide text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-700/50">
              {loading ? (
                <tr>
                  <td colSpan="7" className="py-12 text-center text-slate-500">
                    <div className="flex flex-col items-center justify-center">
                      <div className="w-8 h-8 border-4 border-indigo-500/20 border-t-indigo-500 rounded-full animate-spin mb-3"></div>
                      <p className="animate-pulse">Loading queue...</p>
                    </div>
                  </td>
                </tr>
              ) : alerts.length === 0 ? (
                <tr>
                  <td colSpan="7" className="py-16 text-center text-slate-500">
                    <CheckCircle2 className="w-12 h-12 mx-auto mb-3 text-green-500/50" />
                    <p className="text-lg text-slate-300 mb-1">Queue is empty</p>
                    <p className="text-sm">No alerts matching your criteria.</p>
                  </td>
                </tr>
              ) : (
                alerts.map((alert) => (
                  <tr key={alert.id} className="hover:bg-slate-800/30 transition-colors group">
                    <td className="py-4 px-6 font-mono text-xs text-slate-400">
                      {alert.id.substring(alert.id.length - 8).toUpperCase()}
                    </td>
                    <td className="py-4 px-6">
                      <div className={`inline-flex items-center px-2 py-1 rounded border text-[10px] font-bold tracking-wider ${getSeverityStyle(alert.severity)}`}>
                        {getSeverityIcon(alert.severity)}
                        {alert.severity}
                      </div>
                    </td>
                    <td className="py-4 px-6 max-w-xs truncate text-slate-200">
                      <div className="font-medium">{alert.title}</div>
                      <div className="text-xs text-slate-500 truncate" title={alert.description}>
                        {alert.description}
                      </div>
                    </td>
                    <td className="py-4 px-6 text-slate-300 font-mono text-xs">
                      {alert.sourceIp || 'N/A'}
                    </td>
                    <td className="py-4 px-6 font-medium text-xs tracking-wider">
                      <span className={`${getStatusStyle(alert.status)}`}>
                        {alert.status?.replace('_', ' ')}
                      </span>
                    </td>
                    <td className="py-4 px-6 text-slate-400 text-xs">
                      <div className="flex items-center">
                        <Clock className="w-3 h-3 mr-1.5 opacity-50" />
                        {new Date(alert.updatedAt).toLocaleString()}
                      </div>
                    </td>
                    <td className="py-4 px-6 text-right">
                      {alert.status === 'NEW' && (
                        <button 
                          onClick={() => updateAlertStatus(alert.id, 'INVESTIGATING')}
                          className="px-3 py-1 bg-indigo-500/20 text-indigo-300 hover:bg-indigo-500 hover:text-white rounded text-xs transition-colors border border-indigo-500/30 font-medium"
                        >
                          Investigate
                        </button>
                      )}
                      {alert.status === 'INVESTIGATING' && (
                        <div className="flex justify-end gap-2">
                          <button 
                            onClick={() => updateAlertStatus(alert.id, 'RESOLVED')}
                            className="px-3 py-1 bg-green-500/20 text-green-300 hover:bg-green-500 hover:text-white rounded text-xs transition-colors border border-green-500/30"
                          >
                            Resolve
                          </button>
                          <button 
                            onClick={() => updateAlertStatus(alert.id, 'FALSE_POSITIVE')}
                            className="px-3 py-1 bg-slate-500/20 text-slate-300 hover:bg-slate-500 hover:text-white rounded text-xs transition-colors border border-slate-500/30"
                          >
                            Dismiss
                          </button>
                        </div>
                      )}
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        {/* Pagination */}
        {!loading && totalPages > 1 && (
          <div className="p-4 border-t border-slate-700/50 flex justify-between items-center bg-slate-900/30">
            <span className="text-xs text-slate-400">
              Page {page + 1} of {totalPages}
            </span>
            <div className="flex gap-2">
              <button
                disabled={page === 0}
                onClick={() => setPage(p => p - 1)}
                className="p-1 rounded bg-slate-800 text-slate-300 disabled:opacity-50 hover:bg-slate-700 transition-colors"
              >
                <ChevronUp className="w-5 h-5 -rotate-90" />
              </button>
              <button
                disabled={page === totalPages - 1}
                onClick={() => setPage(p => p + 1)}
                className="p-1 rounded bg-slate-800 text-slate-300 disabled:opacity-50 hover:bg-slate-700 transition-colors"
              >
                <ChevronDown className="w-5 h-5 -rotate-90" />
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default Alerts;