server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/sentinelcore

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration-ms: 86400000 # 24 hours

sentinel:
  admin:
    name: ${SENTINEL_ADMIN_NAME:Admin}
    email: ${SENTINEL_ADMIN_EMAIL:admin@sentinelcore.in}
    password: ${SENTINEL_ADMIN_PASSWORD:Admin@123}
    department: ${SENTINEL_ADMIN_DEPARTMENT:Security Operations}
