server:
  port: 8080

spring:
  application:
    name: sentinelcore
  datasource:
    url: jdbc:h2:mem:sentinelcore;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  secret: "9a72df82a7f5e8f498c48a73cd2e391b1a772f9d51e73e9cfde081395cf943cf"
  expirationMs: 86400000
